### ISSUE TITLE
Slider shows wrong values when using hidden directive.

### ISSUE THREAD

**Issue by orzolp** [angular-slider/ng5-slider#106]
Hello,
Slider acts weird when it's wrapped in container with hidden directive. It's bugged when hidden value is true at start. Slider will start to work properly if we change values. Fork link (stackblitz):
https://stackblitz.com/edit/ng5-slider-simple-slider-example-xgisko
I added second slider so you can see that problem is related to hidden directive only.
In some places in my project it's easier to use hidden than *ngIf - with ngIf directive, everythings seems fine. Can you help with this?

Thanks

**Comment by piotrdz** [comment]
This is an often reported issue (see [KNOWN_ISSUES.md](https://github.com/angular-slider/ng5-slider/blob/master/KNOWN_ISSUES.md)), which I haven't been able to fix satisfactorily until now, though there are some workarounds available.

However, I recently learned about [MutationObserves](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver), which is a JavaScript feature that can solve this problem.

Therefore, I will try to fix this in next release.

**Comment by piotrdz** [comment]
As it turned out, MutationObserver API would not help in this scenario, but I found another way to solve this.

[ResizeObserver API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) solves the problem quite nicely, without the need to use the previous workaround with `manualRefresh`. The only downside is that it is only supported on some of the newest browsers, currently only Chrome >= 64 and Opera >= 51. But support for other browsers should be added quite soon, so I consider this good enough.

Fix is now available in master and will go out in next release.

**Comment by piotrdz** [comment]
Fix now released in v1.2.1.
