### ISSUE TITLE
High value pointer starts at 0 instead of specified position on Safari/FF

### ISSUE THREAD

**Issue by willhs** [angular-slider/ng5-slider#118]
I set the highValue attribute to some non-0 value and it still initially displays at the 0 position, on Safari and FF. 

My slider is hidden by default which might influence things; may be related to recently resolved issue: https://github.com/angular-slider/ng5-slider/issues/106.

On chrome it works correctly.

**Comment by piotrdz** [comment]
As I described in comments on #106, this is because I used [ResizeObserver API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to solve this problem. It is currently available in Chrome and Opera; other browsers will add support for it in upcoming versions.

As a workaround, you can use `manualRefresh` input to trigger a refresh. See [manual refresh demo](https://angular-slider.github.io/ng5-slider/demos#manual-refresh-slider) for how to use it.
