### ISSUE TITLE
Why is cordova.js interfering with ng5-slider?

### ISSUE THREAD

**Issue by nunoarruda** [angular-slider/ng5-slider#198]
Here's an animated gif showing an index.html that does not include cordova.js and an index-cordova.html that includes cordova.js:
![ng5-slider-cordova-issue](https://user-images.githubusercontent.com/1189149/87330529-3cf0d000-c528-11ea-9fde-82f2de4a42b8.gif)

Notice that ng5-slider on index-cordova.html behaves strangely. Any idea why and how? Any workarounds?

Repository to reproduce the issue: https://github.com/nunoarruda/ng5-slider-cordova

I've opened a similar issue on the cordova repository: https://github.com/apache/cordova/issues/228

**Comment by piotrdz** [comment]
@nunoarruda I see that this has been investigated from cordova side in apache/cordova#228 and the problem lies in how cordova and Angular override native browser functions. There is also a suggested workaround for this problem.

This has nothing to do with the slider component itself, so I will close this ticket.
