### ISSUE TITLE
Ionic 3 Support and Use case inside the <ion-list>

### ISSUE THREAD

**Issue by 009topersky** [angular-slider/ng5-slider#20]
Good day sir!

I Just want to ask if  the module have a support on ionic 3

i want to use it **ng5-slider** on my ionic app inside  the ion-list -> ion-items

**Put this vertical ng5-slider**
![image](https://user-images.githubusercontent.com/5698315/45741415-17475800-bc2a-11e8-96cf-82b18abec789.png)

**Here at the rightmost part**

![image](https://user-images.githubusercontent.com/5698315/45741433-21695680-bc2a-11e8-8b73-a44af7db3b2a.png)

**To be look like this**

![image](https://user-images.githubusercontent.com/5698315/45741862-37c3e200-bc2b-11e8-9def-b9e2bea8a33e.png)

any help will be appreciated.
Thanks

**Comment by piotrdz** [comment]
Hi. This is the first time I hear about Ionic, but it seems to be based on Angular, so I imagine it's like using any other Angular module in your application, according to this: http://masteringionic.com/blog/2017-04-15-using-angular-modules-in-ionic-applications/

**Comment by piotrdz** [comment]
I've played a little bit with Ionic and I've verified that the slider does work in Ionic, like in [this Stackblitz](https://stackblitz.com/edit/ionic-dzpjcq?file=pages%2Fhome%2Fhome.html).

I can't advise more about how to place the slider in Ionic components, but I imagine it should be possible.

But since this is not an issue with the slider component, but rather a question about Ionic, I'll close this ticket.
