### ISSUE TITLE
Can't bind to 'formControl' since it isn't a known property of 'ng5-slider'

### ISSUE THREAD

**Issue by tsegato** [angular-slider/ng5-slider#42]
I have following in an Angular 6 app:
 html:
```
<p>Value: {{sliderControl.value}}</p>
<ng5-slider [options]="options" [formControl]="sliderControl"></ng5-slider>
```

app.module.ts:
import { Ng5SliderModule } from 'ng5-slider';

component.ts:
import { FormGroup,FormControl } from '@angular/forms';
import { Options,Ng5SliderModule } from 'ng5-slider';

 minValue: number = 20;
 maxValue: number = 80;
  options: Options = {
    floor: 0,
    ceil: 100,
    step: 
  };

I get following error:
Can't bind to 'formControl' since it isn't a known property of 'ng5-slider'.
1. If 'ng5-slider' is an Angular component and it has 'formControl' input, then verify that it is part of this module.
2. If 'ng5-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

          <p>Value: {{sliderControl.value}}</p>
          <ng5-slider [options]="options" [ERROR ->][formControl]="sliderControl"></ng5-slider>

**Comment by piotrdz** [comment]
Two things:
 - you should import `ReactiveFormsModule` in your app module - this is why Angular is complaining about `formControl`,
 - instead of `minValue` and `maxValue` in your component class, you need a `sliderControl` field:
` sliderControl: FormControl = new FormControl([20, 80]);`

See [this StackBlitz](https://stackblitz.com/edit/ng5-slider-reactive-forms-example?file=src%2Fapp%2Fapp.component.ts) for a full example.

I hope this helps.

**Comment by tsegato** [comment]
Worked! Thanks a lot, highly appreciated!
