### ISSUE TITLE
Ability to have a custom slider template

### ISSUE THREAD

**Issue by sjyn** [angular-slider/ng5-slider#46]
In the AngularJS library that this library is based on, there was a way to set a custom template on the slider via an `rz-slider-tpl-url` directive.

```html
<rzslider ...
  rz-slider-tpl-url="path/to/template.html">
```

Is there a way to do this in this library/is this a planned feature for this library? The documentation doesn't seem to say anything about this functionality.

**Comment by piotrdz** [comment]
No, sorry, I have no plans to support custom templates in Angular 5+.

Unlike angularjs, Angular 5+ requires each component to have a static template, able to be resolved at compile time.

While there are some workarounds that could be applied, like transcluding user-specified content, the problem is that managing code like this very quickly becomes borderline insane. I already went through something similar to support custom tooltips. This was to get rid of dependency on ng-bootstrap, and that's about as far as I'm willing to go.

**Comment by sjyn** [comment]
Thanks for getting back to me so quick!

I think I'll fork this repo and give it a shot since there's not really a nice workaround for my particular use case.

**Comment by piotrdz** [comment]
Yes, forking will be an easier option.
