### ISSUE TITLE
Synchronizing 2 input values with the slider in reactive forms

### ISSUE THREAD

**Issue by ahmadmu** [angular-slider/ng5-slider#55]
In my reactive form data structure I have 2 separate FormControls for my "value" and "highValue", to be able to attach them to 2 input fields so that the user can write both separately. The slider however only accepts 1 array of a "value" and "highValue", which means that binding the values seperately is not possible with this approach, and the slider cannot get synchronized with 2 input fields. Is there another way to bind 2 form controls to the slider, and if not would it be possible to add that functionality in the future? (Maybe turn the [value, highValue] array into a FormArray with 2 FormControls?)

**Comment by piotrdz** [comment]
Ah, well, when skimming the docs eariler, I thought there was a way of coercing `FormArray` or `FormGroup` to act in this way, but as it turns out, it's not possible.

The whole concept of reactive forms is based on one-to-one mapping between `FormControl` and the input component. There is no way to solve your problem using purely reactive forms. This is due to two facts:
 - single `FormControl` cannot be bound to multiple inputs (see https://github.com/angular/angular/issues/14451), so you can't bind a `value/highValue` `FormControl` once to an input box and then again to a slider,
 - a collection of `FormControl`s embedded in `FormArray` or `FormGroup` does **not** act as a `FormControl` itself, so there is no way of binding an array or group of `[value, highValue]` `FormControl`s to the slider.

I'm afraid the only way of doing what you'd like to achieve is to write your own wrapper code using plain old model bindings.

**Comment by ahmadmu** [comment]
Yeah it seems like that's not possible with ControlValueAccessor. Though wouldn't it be technically possible to pass in the controls to the component using normal data binding through [value] and [highValue]? 

For now I'm catching the values from the ng5-slider component using (valueChange) and (highValueChange) and patching the control values in my component, and it seems to be working pretty well, so passing in the controls might not be that necessary. Thanks.

**Comment by piotrdz** [comment]
@ahmadmu: Technically, it is possible to pass anything in `value` and `highValue`, but it's a non-standard way of using the reactive forms API, and it would lead to more complexity in code handling model value synchronisation. In the end, I'm not sure it's worth adding the code considering the maintenance effort, and the fact that you can work around the issue with custom code anyway.
