### ISSUE TITLE
Set focus programmatically

### ISSUE THREAD

**Issue by sevaru** [angular-slider/ng5-slider#64]
I have a section with sliders, which shows on button click.

I need to focus on first slider when section is shown.

Is it possible to programmatically set focus on slider?

as for now i'm using

```
//html
<div #slider>
    <ng5-slider [(value)]="value" [options]="sliderOptions"></ng5-slider>
 </div>

// ts
@ViewChild('slider') slider: ElementRef;

ngAfterViewInit(): {
    this.slider.nativeElement.querySelector('.ng5-slider-pointer-min').focus();
}
```

**Comment by piotrdz** [comment]
No, it's not currently supported, but your workaround is a correct way to do it.

I could add a way of triggering focus programmatically to the slider. I think a good way of solving this would be a new input `triggerFocus`- it would take an observable as input and when the observable emits a value, it would set focus on the slider. The observable can also take Low/High slider pointer as argument, so that you can specify which one to use.

Would that work for you?

**Comment by sevaru** [comment]
Yeah, that absolutely would work for me.
Thanks.

**Comment by piotrdz** [comment]
I added this feature to the v1.1.4 release. See the [new demo](https://angular-slider.github.io/ng5-slider/demos#trigger-focus-slider) for example of use.
