### ISSUE TITLE
Errors In Production Build

### ISSUE THREAD

**Issue by shivarajnaidu** [angular-slider/ng5-slider#7]
When I tried to build a production version of my app it's creating error ...

![image](https://user-images.githubusercontent.com/12374494/43002514-aa1c2cc8-8c46-11e8-9888-870ebf810f9d.png)

If possible please remove the dependency from slider library.. and publish the update

**Comment by Dovernh** [comment]
I am experiencing the same issue. I do have ngx-bootstrap in package.json. Tried adding ng-bootstrap. Same error. Would like no dependency to bootstrap

**Comment by piotrdz** [comment]
This problem is due to the way AOT (ahead-of-time) compilation works in Angular. If it's an option, can you build with AOT compilation disabled?
`ng build --prod --no-aot`

Unfortunately, there is currently no real way of having optional dependencies in Angular when you use directives from other modules. I tried to work around it by putting conditional logic that would detect whether ng-bootstrap is available in runtime, or not, but as seen here, it fails with AOT compilation.

I'm now working on a better solution, but I'll need some more time to polish it a little bit.

**Comment by shivarajnaidu** [comment]
but we can remove the dependency of bootstrap altogether right ? (we can use custom builtin solution or some other generic library instead of using bootstrap I think.. right ?)

**Comment by piotrdz** [comment]
If you build with AOT disabled, you don't need bootstrap even now. You can remove it from package.json and the project should build just fine, so long as you don't try AOT.

My fix will be to provide the user with the option to specify a custom template which will define how tooltips are shown. That way, the slider will not depend on any 3rd party library, and the users can choose whether to use bootstrap, something else, or if they don't care about tooltips, they will just not be displayed.

**Comment by sphrases** [comment]
Hey, I really enjoy Ng slider. Unfortunately I can not use it when npm installing my angular 6 application due to some tools requiring aot being enabled. Do you think it can be fixed otherwise? 
Bootstrap 2.2.0 is required for some other tools, so I can't install the required version for that tool that is older then 2.2.0. Can I somehow remove the function of the tooltips? I dont require them for my program. 
(am a noob with this, so I am asking)

Really great tool btw. 
Exactly what I need

**Comment by dagardiner** [comment]
I spent way too long troubleshooting before I found this thread, glad I'm not going crazy.  Is there a timeline for an update, or anything I can do to assist?  We're pushing to a final UAT soon, and this is blocking a CI build process.

**Comment by piotrdz** [comment]
Apologies for the delay. I was on holiday with limited internet access. The fix is now released in version 1.1.0.

Tooltips are now rendered using standard `title` HTML attribute, or if specified, using user-provided template, which can use ng-bootstrap or any other 3rd party library. I updated the documentation and the Github pages demos to reflect the changes.

**Comment by dagardiner** [comment]
Awesome - you rock, thank you!
