### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by tsegato** [angular-slider/ng5-slider#78]
Thanks for a great work! I am trying to style the slider to have smaller pointer. In my .scss file I have following:
  .ng5-slider {
    background-color: red !important;
  }
  .ng5-slider .ng5-slider-pointer{
    height: 16px !important;
    background-color: red !important;
  }

html:
     <div class="width:100%" class="test">
       
                <p>Value: <input type="number" [(ngModel)]="value"></p>
                <ng5-slider [(value)]="value" [options]="options"></ng5-slider>
            </div>

However styling does not take affect. Shouldnt you be able to override styles or am I missing something here?

**Comment by Natasha-Rego** [comment]
Try ::ng-deep

**Comment by piotrdz** [comment]
You either need to apply `::ng-deep`, or add additional selectors to make the CSS more specific (e.g. add a `custom-slider` class to your slider and use `.custom-slider .ng5-slider`).

Please refer to the [Styling guide](https://github.com/angular-slider/ng5-slider/blob/master/STYLING.md) for more information.

Since this example is working with `::ng-deep` ([StackBlitz](https://stackblitz.com/edit/ng5-slider-issue-78?file=src/app/app.component.scss)), I'm closing the ticket.
