### ISSUE TITLE
Slider Events

### ISSUE THREAD

**Issue by Dovernh** [angular-slider/ng5-slider#9]
Perhaps I missed it, but I'm not seeing any documented events from the slider. After reviewing the code I do see some events emitted. I'm only looking to check if the slider values have been changed by the user, "dirty". I am wondering whether it's safe to use the valuechanged and highValueChanged events?  Perhaps you have another recommendation?

**Comment by mikhailgrekov** [comment]
there is a valueChange event

**Comment by piotrdz** [comment]
`valueChange` and `valueChangeHigh` events come from two-way binding of `value` and `valueHigh`. I left out the other events intentionally, because I wanted to focus on basic functionality first.

I agree that more events would be a good idea now that the library is stable. I'll have a look again at what events I can support and I'll include the events in documentation.

**Comment by HeloiseH** [comment]
I am trying to use valueChange, but when I used it, I can't access to 'this' (error : ERROR TypeError: "this is undefined"). So value change detection is useless because I can't adapt my application according to the value. Is this normal or am I doing something wrong ?

**Comment by piotrdz** [comment]
I added support for user-initiated events in v1.1.1 based on `onStart`, `onChange` and `onEnd` from the old library. I updated documentation and added an example with events to the demo app.
